// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	ID         int64            `json:"id"`
	UserID     int64            `json:"user_id"`
	Token      string           `json:"token"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

type User struct {
	ID           int64            `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
